project:
  name: crypto_volatility_ml
  random_seed: 42

data:
  exchange: "binance"

  symbols:
    BTC: BTCUSDT
    ETH: ETHUSDT
    SOL: SOLUSDT
    BNB: BNBUSDT

  interval: "1d"

  start_date: "2021-01-01"
  end_date: null

  raw_dir: data/raw
  interim_dir: data/interim
  processed_dir: data/processed

features:
  realized_volatility: 
    method: garman_klass

  rolling_window:
    - 7
    - 30

model:
  target_horizon: 1

portfolio:
  initial_capital: 1000000

logging:
  level: INFO